Repository tenstorrent/tt-metal, pull requests merged in 2024-11, with the labels that each got.

#14241 Support ROPE op for Llama in decode mode
  tests/tt_eager/python_api_testing/unit_testing/misc/test_rotary_embedding_llama.py
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/device/kernels/compute/rotary_embedding_llama_sharded.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/device/rotary_embedding_llama_device_operation.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/device/rotary_embedding_llama_device_operation.hpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/device/rotary_embedding_llama_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/device/rotary_embedding_llama_program_factory.hpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/rotary_embedding_llama.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/rotary_embedding_llama.hpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/rotary_embedding_llama_pybind.cpp
Labels: LLMs on Metal

#14647 #0: Update dprint_server.cpp
  tt_metal/impl/debug/dprint_server.cpp
Labels: cleanup, arch_name

#14639 #14638: Update tt_metal_profiler.cpp
  tt_metal/tools/profiler/tt_metal_profiler.cpp
Labels: cleanup, arch_name

#14621 #14620: Remove unnecessary ARCH_NAME specific includes from llrt.hpp
  tt_metal/llrt/llrt.cpp
  tt_metal/llrt/llrt.hpp
  ttnn/cpp/ttnn/operations/core/compute_kernel/compute_kernel_config.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/create_qkv_heads/device/create_qkv_heads_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/create_qkv_heads_from_separate_tensors/device/create_qkv_heads_from_separate_tensors_device_operation.cpp
  ttnn/cpp/ttnn/operations/reduction/topk/device/topk_op.cpp
  ttnn/cpp/ttnn/operations/reduction/topk/device/topk_program_factory.hpp
Labels: cleanup, arch_name

#14527 Create Tutorial - Add Two Integers in a Baby RISC-V.md
  tech_reports/prog_examples/add_2_integers_in_riscv/Tutorial - Add Two Integers in a Baby RISC-V.md
Labels: doc_cat: ttnn

#14774 #14581: Remove deprecated UMD API host_addr_params
  tt_metal/llrt/tt_cluster.cpp
  tt_metal/llrt/tt_cluster.hpp
Labels: cleanup, arch_name

#14769 #14580: Remove usage of noc_parameters.h from cq_commands.hpp
  tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/test_prefetcher.cpp
  tt_metal/impl/device/device.cpp
  tt_metal/impl/dispatch/command_queue.cpp
  tt_metal/impl/dispatch/cq_commands.hpp
  tt_metal/impl/dispatch/device_command.hpp
  tt_metal/impl/dispatch/kernels/cq_prefetch.cpp
Labels: cleanup, arch_name

#14708 #14707: refactoring return optional tensors
  tests/ttnn/unit_tests/operations/test_moreh_group_norm.py
  ttnn/cpp/ttnn/decorators.hpp
  ttnn/cpp/ttnn/operations/examples/example_multiple_return/example_multiple_return.cpp
  ttnn/cpp/ttnn/operations/examples/example_multiple_return/example_multiple_return.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_adam/moreh_adam.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_adam/moreh_adam.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_adamw/moreh_adamw.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_adamw/moreh_adamw.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_dot_backward/moreh_dot_backward.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_dot_backward/moreh_dot_backward.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_group_norm/moreh_group_norm.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_group_norm/moreh_group_norm.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_group_norm_backward/moreh_group_norm_backward.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_group_norm_backward/moreh_group_norm_backward.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_layer_norm/moreh_layer_norm.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_layer_norm/moreh_layer_norm.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_layer_norm_backward/moreh_layer_norm_backward.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_layer_norm_backward/moreh_layer_norm_backward.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_linear_backward/moreh_linear_backward.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_linear_backward/moreh_linear_backward.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_matmul_backward/moreh_matmul_backward.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_matmul_backward/moreh_matmul_backward.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_sgd/moreh_sgd.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_sgd/moreh_sgd.hpp
  ttnn/cpp/ttnn/run_operation_inl.hpp
Labels: moreh

#14792 #14628: Remove ARCH_NAME specific parameter from kernel.cpp
  tt_metal/impl/kernels/kernel.cpp
  tt_metal/impl/kernels/kernel.hpp
  tt_metal/llrt/hal.cpp
  tt_metal/llrt/hal.hpp
Labels: cleanup, arch_name

#14801 #0: fixed idle core assignment mismatch for sdpa decode in sharded low batch case
  tests/tt_eager/python_api_testing/unit_testing/misc/test_scaled_dot_product_attention_decode.py
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/sdpa_decode_program_factory.cpp
Labels: kernels, P0, llama3, flash-decode, flash-attention

#14866 14517: making all-gather and barrier support tiny-tiles
  tests/ttnn/unit_tests/operations/ccl/test_all_gather.py
  tests/ttnn/unit_tests/operations/ccl/test_all_gather_TG_post_commit.py
  tests/ttnn/unit_tests/operations/ccl/test_all_gather_matmul.py
  tests/ttnn/unit_tests/operations/ccl/test_all_gather_nightly.py
  tests/ttnn/unit_tests/operations/ccl/test_barrier_t3000_frequent.py
  tt_metal/hw/inc/dataflow_api.h
  ttnn/cpp/ttnn/distributed/api.cpp
  ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp
  ttnn/cpp/ttnn/operations/ccl/all_gather/device/kernels/dataflow/worker_interleaved_ring_gather_receive_writer.cpp
  ttnn/cpp/ttnn/operations/ccl/all_gather/device/kernels/dataflow/worker_interleaved_ring_gather_send_reader.cpp
  ttnn/cpp/ttnn/operations/ccl/all_gather/device/kernels/dataflow/worker_interleaved_ring_gather_send_writer.cpp
  ttnn/cpp/ttnn/operations/ccl/all_gather/device/multi_core/all_gather_op_multi_core.cpp
  ttnn/cpp/ttnn/operations/ccl/ccl_common.cpp
  ttnn/cpp/ttnn/operations/ccl/ccl_common.hpp
  ttnn/cpp/ttnn/operations/ccl/ccl_host_datastructures.cpp
  ttnn/cpp/ttnn/operations/ccl/ccl_host_datastructures.hpp
  ttnn/cpp/ttnn/tensor/tensor.cpp
  ttnn/cpp/ttnn/tensor/tensor_utils.cpp
Labels: op_cat: ccl

#14380 #14379: Support pad_value for ttnn.from_torch
  tests/ttnn/unit_tests/operations/test_moreh_bmm.py
  tests/ttnn/unit_tests/operations/test_moreh_mean.py
  tests/ttnn/unit_tests/operations/test_moreh_norm.py
  tests/ttnn/unit_tests/operations/test_utils.py
  ttnn/ttnn/operations/core.py
Labels: moreh

#14936 #14934: Comment Llama3-70B frequent tests. Update Mixtral/LLama3-1B perf targets.
  .github/workflows/t3000-frequent-tests-impl.yaml
  models/demos/llama3/tests/test_llama_perf.py
  models/demos/t3000/mixtral8x7b/tests/test_mixtral_perf.py
Labels: LLMs on Metal

#14667 #14665: add new moreh_clip_grad_norm and test in ttnn
  tests/ttnn/unit_tests/operations/test_moreh_clip_grad_norm.py
  ttnn/CMakeLists.txt
  ttnn/cpp/ttnn/deprecated/tt_dnn/op_library/CMakeLists.txt
  ttnn/cpp/ttnn/deprecated/tt_dnn/op_library/moreh_clip_grad_norm/moreh_clip_grad_norm_op.cpp
  ttnn/cpp/ttnn/deprecated/tt_dnn/op_library/moreh_clip_grad_norm/moreh_clip_grad_norm_op.hpp
  ttnn/cpp/ttnn/deprecated/tt_dnn/op_library/moreh_clip_grad_norm/moreh_clip_grad_norm_step1/moreh_clip_grad_norm_step1.cpp
  ttnn/cpp/ttnn/deprecated/tt_dnn/op_library/moreh_clip_grad_norm/moreh_clip_grad_norm_step2/moreh_clip_grad_norm_step2.cpp
  ttnn/cpp/ttnn/deprecated/tt_dnn/op_library/moreh_clip_grad_norm/moreh_clip_grad_norm_step3/moreh_clip_grad_norm_step3.cpp
  ttnn/cpp/ttnn/deprecated/tt_lib/csrc/operations/primary/module.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_pybind.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_pybind.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step1/device/kernels/moreh_clip_grad_norm_step1_kernel.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step1/device/kernels/reader_moreh_clip_grad_norm_step1.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step1/device/kernels/writer_moreh_clip_grad_norm_step1.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step1/device/moreh_clip_grad_norm_step1_device_operation.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step1/device/moreh_clip_grad_norm_step1_device_operation.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step1/device/moreh_clip_grad_norm_step1_program_factory.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step2/device/kernels/moreh_clip_grad_norm_step2_kernel.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step2/device/kernels/reader_moreh_clip_grad_norm_step2.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step2/device/kernels/writer_moreh_clip_grad_norm_step2.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step2/device/moreh_clip_grad_norm_step2_device_operation.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step2/device/moreh_clip_grad_norm_step2_device_operation.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step2/device/moreh_clip_grad_norm_step2_program_factory.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step3/device/kernels/moreh_clip_grad_norm_step3_kernel.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step3/device/kernels/reader_moreh_clip_grad_norm_step3.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step3/device/kernels/writer_moreh_clip_grad_norm_step3.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step3/device/moreh_clip_grad_norm_step3_device_operation.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step3/device/moreh_clip_grad_norm_step3_device_operation.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step3/device/moreh_clip_grad_norm_step3_program_factory.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_pybind.cpp
  ttnn/ttnn/operations/moreh.py
Labels: moreh

#14908 Move NUM_CIRCULAR_BUFFERS to hw/inc
  tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/common.h
  tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/test_prefetcher.cpp
  tt_metal/hostdevcommon/common_runtime_address_map.h
  tt_metal/hw/inc/blackhole/eth_l1_address_map.h
  tt_metal/hw/inc/blackhole/noc_nonblocking_api.h
  tt_metal/hw/inc/circular_buffer.h
  tt_metal/hw/inc/dataflow_api.h
  tt_metal/hw/inc/debug/sanitize_noc.h
  tt_metal/hw/inc/grayskull/noc_nonblocking_api.h
  tt_metal/hw/inc/risc_attribs.h
  tt_metal/hw/inc/risc_common.h
  tt_metal/hw/inc/wormhole/noc_nonblocking_api.h
  tt_metal/impl/buffers/circular_buffer_types.hpp
  tt_metal/impl/device/device.cpp
  tt_metal/impl/program/program.cpp
  tt_metal/jit_build/data_format.cpp
  tt_metal/jit_build/genfiles.cpp
Labels: cleanup, arch_name

#14920 Move NOC_0_X/Y behind Hal
  CMakeLists.txt
  tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/common.h
  tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/test_prefetcher.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_bi_tunnel_2ep.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_bi_tunnel_4ep.cpp
  tests/tt_metal/tt_metal/unit_tests_common/watcher/test_noc_sanitize.cpp
  tests/tt_metal/tt_metal/unit_tests_fast_dispatch/common/command_queue_fixture.hpp
  tt_metal/hostdevcommon/common_runtime_address_map.h
  tt_metal/impl/debug/watcher_device_reader.cpp
  tt_metal/impl/device/device.cpp
  tt_metal/impl/program/program.cpp
  tt_metal/jit_build/genfiles.cpp
  tt_metal/llrt/hal.hpp
Labels: cleanup, arch_name

#14943 Reduce dependence on ARCH_NAME in dev_msgs.h
  tt_metal/hw/inc/dev_msgs.h
  tt_metal/impl/debug/sanitize_noc_host.hpp
  tt_metal/llrt/blackhole/bh_hal_active_eth.cpp
  tt_metal/llrt/blackhole/bh_hal_idle_eth.cpp
  tt_metal/llrt/blackhole/bh_hal_tensix.cpp
  tt_metal/llrt/grayskull/gs_hal.cpp
  tt_metal/llrt/hal_asserts.hpp
  tt_metal/llrt/llrt.hpp
  tt_metal/llrt/wormhole/wh_hal_active_eth.cpp
  tt_metal/llrt/wormhole/wh_hal_idle_eth.cpp
  tt_metal/llrt/wormhole/wh_hal_tensix.cpp
Labels: cleanup, arch_name

#14927 #14546: Fix moreh_adamw power_tile reduce performance
  ttnn/cpp/ttnn/operations/moreh/moreh_adamw/device/kernels/moreh_adamw.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_adamw/device/kernels/reader_moreh_adamw.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_adamw/device/multi_core_program_factory.cpp
Labels: bug, moreh

#14878 #14634: Remove usage of ARCH_NAME sp constants MEM_L1_SIZE
  tt_metal/impl/debug/sanitize_noc_host.hpp
  tt_metal/impl/device/device.cpp
  tt_metal/impl/dispatch/command_queue_interface.hpp
  tt_metal/llrt/blackhole/bh_hal_active_eth.cpp
  tt_metal/llrt/blackhole/bh_hal_idle_eth.cpp
  tt_metal/llrt/blackhole/bh_hal_tensix.cpp
  tt_metal/llrt/grayskull/gs_hal.cpp
  tt_metal/llrt/hal.hpp
  tt_metal/llrt/wormhole/wh_hal_active_eth.cpp
  tt_metal/llrt/wormhole/wh_hal_idle_eth.cpp
  tt_metal/llrt/wormhole/wh_hal_tensix.cpp
Labels: cleanup, arch_name

#15286 15178: fix dprint race condition
  tt_metal/hostdevcommon/dprint_common.h
  tt_metal/impl/debug/dprint_server.cpp
Labels: bug

#15364 matmul fix check that was looking into output_tensor instead of the input_tensor_b
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp
Labels: bug

#15312 Move relocate_dev_addr behind Hal
  tt_metal/llrt/blackhole/bh_hal.cpp
  tt_metal/llrt/grayskull/gs_hal.cpp
  tt_metal/llrt/hal.hpp
  tt_metal/llrt/llrt.cpp
  tt_metal/llrt/llrt.hpp
  tt_metal/llrt/wormhole/wh_hal.cpp
Labels: cleanup, arch_name

#15405 Add #pragma once directive to kernel headers
  ttnn/cpp/ttnn/deprecated/tt_dnn/kernels/dataflow/moreh_common.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_cumsum/device/kernels/utils.hpp
  ttnn/cpp/ttnn/operations/moreh/moreh_getitem/device/moreh_getitem_tilized_kernels/common.hpp
Labels: moreh

#15081 #0: LLM Tech Report: Intro
  tech_reports/LLMs/llms.md
Labels: LLMs on Metal

#15104 LLM tech report performance analysis
  models/perf/images/example_perf_report.png
  tech_reports/LLMs/images/4.6-op-to-op-gap.png
  tech_reports/LLMs/images/4.6-overview.png
  tech_reports/LLMs/llms.md
Labels: LLMs on Metal

#14964 Support for new matmul1d op with gather_in0
  tests/tt_eager/python_api_testing/unit_testing/misc/test_matmul_1d_gather_in0.py
  ttnn/cpp/ttnn/operations/matmul/device/kernels/compute/bmm_large_block_zm_fused_bias_activation_gathered.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in0_ring_all_gather.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in1_ring_all_gather.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op.hpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_1d_program_factory.cpp
  ttnn/cpp/ttnn/operations/matmul/matmul_pybind.cpp
Labels: metal, LLMs on Metal

#15315 Make MEM_LOCAL_BASE accessible behind Hal
  tt_metal/llrt/blackhole/bh_hal_tensix.cpp
  tt_metal/llrt/grayskull/gs_hal.cpp
  tt_metal/llrt/hal.hpp
  tt_metal/llrt/llrt.cpp
  tt_metal/llrt/wormhole/wh_hal_tensix.cpp
Labels: cleanup, arch_name

#15541 #15540: support bfp8_b 1d tensor in ttnn
  ttnn/ttnn/operations/core.py
Labels: moreh, feature

#15543 #15542: Add dtype to `to_torch`
  tests/ttnn/unit_tests/test_to_dtype.py
  ttnn/ttnn/operations/core.py
Labels: moreh, feature

#15545 Add performance and accuracy configurations to Llama 3
  models/demos/llama3/PERF.md
  models/demos/llama3/README.md
  models/demos/llama3/demo/demo.py
  models/demos/llama3/lt
  models/demos/llama3/tests/test_llama_accuracy.py
  models/demos/llama3/tests/test_llama_model.py
  models/demos/llama3/tests/test_llama_model_prefill.py
  models/demos/llama3/tests/test_llama_perf.py
  models/demos/llama3/tt/llama_mlp.py
  models/demos/llama3/tt/model_config.py
Labels: LLMs on Metal, llama3
