Repository tenstorrent/tt-metal, pull requests merged in 2025-05, with the labels that each got.

#20733 Update xtensor stack and fix includes.
  dockerfile/Dockerfile
  tests/ttnn/unit_tests/gtests/tensor/test_partition.cpp
  tests/ttnn/unit_tests/gtests/tensor/test_vector_conversion.cpp
  tests/ttnn/unit_tests/gtests/tensor/test_xtensor_conversion.cpp
  third_party/CMakeLists.txt
  third_party/xtensor-blas.patch
  third_party/xtensor.patch
  third_party/xtl.patch
  tt-train/cmake/dependencies.cmake
  tt-train/tests/core/clip_grad_norm_test.cpp
  ttnn/cpp/ttnn/tensor/xtensor/partition.cpp
  ttnn/cpp/ttnn/tensor/xtensor/xtensor_all_includes.hpp
Labels: community

#21489 SELU: Fix incorrect formula and reduce asymptotic error
  ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp
Labels: op_cat: eltwise, accuracy

#21901 Added script for checking for mismatches in number of NOC transactions
  scripts/debugging_scripts/check_noc_status.py
Labels: feature-request

#21925 tt_transformers/README.md: Description for non-uniform decoders
  models/tt_transformers/README.md
Labels: docs

#22091 [skip ci] Update get_started.rst, changing #2 - removed individual mo…
  docs/source/ttnn/ttnn/get_started.rst
Labels: P0
