Repository tenstorrent/tt-metal, pull requests merged in 2025-01, with the labels that each got.

#14396 Adapt to tt-system-tools hugepages configuration
  .github/actions/ensure-active-weka-mount/action.yml
  .github/scripts/cloud_utils/mount_weka.sh
  .github/workflows/full-regressions-and-models.yaml
  .github/workflows/package-and-release.yaml
  .github/workflows/perf-device-models-impl.yaml
  .github/workflows/single-card-demo-tests-impl.yaml
  .github/workflows/test-dispatch.yaml
  infra/machine_setup/scripts/setup_hugepages.py
Labels: infra-ci, P1

#16135 #16134: add test cases for pre-allocated CreateBuffer / ttnn::event_query
  tests/tt_metal/tt_metal/api/test_dram.cpp
  tests/ttnn/unit_tests/gtests/test_async_runtime.cpp
Labels: moreh

#16475 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: community

#16455 Xuncai/ccl global sem
  tests/ttnn/unit_tests/gtests/ccl/test_fabric_erisc_data_mover_loopback_with_workers.cpp
  tests/ttnn/unit_tests/operations/ccl/test_all_gather_TG_post_commit.py
  tests/ttnn/unit_tests/operations/ccl/test_ccl_common.py
  tests/ttnn/unit_tests/operations/ccl/test_new_all_gather.py
  tests/ttnn/unit_tests/operations/ccl/test_reduce_scatter_TG_nightly.py
  tests/ttnn/unit_tests/operations/ccl/test_reduce_scatter_async.py
  tests/ttnn/unit_tests/test_global_semaphore.py
  ttnn/cpp/pybind11/global_semaphore.cpp
  ttnn/cpp/ttnn/global_semaphore.cpp
  ttnn/cpp/ttnn/global_semaphore.hpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/all_gather_async.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/all_gather_async.hpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/all_gather_async_pybind.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/all_gather_async_op.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/all_gather_async_op.hpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/all_gather_async_program.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/reduce_scatter_async/device/reduce_scatter_async_op.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/reduce_scatter_async/device/reduce_scatter_async_op.hpp
  ttnn/cpp/ttnn/operations/experimental/ccl/reduce_scatter_async/device/reduce_scatter_async_program.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/reduce_scatter_async/reduce_scatter.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/reduce_scatter_async/reduce_scatter.hpp
  ttnn/cpp/ttnn/operations/experimental/ccl/reduce_scatter_async/reduce_scatter_pybind.cpp
  ttnn/ttnn/__init__.py
Labels: P1, op_cat: ccl

#16505 Remove ARCH_NAME specific includes from erisc_datamover_builder
  .clang-format-ignore
  tests/ttnn/unit_tests/gtests/ccl/test_ccl_helpers.cpp
  tests/ttnn/unit_tests/gtests/ccl/test_erisc_data_mover_with_workers.cpp
  tests/ttnn/unit_tests/gtests/ccl/test_fabric_erisc_data_mover_loopback_with_workers.cpp
  tt_metal/experimental/hal.cpp
  tt_metal/experimental/hal.hpp
  ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp
  ttnn/cpp/ttnn/operations/ccl/barrier/device/host/barrier_full_worker_grid.cpp
  ttnn/cpp/ttnn/operations/ccl/ccl_common.cpp
  ttnn/cpp/ttnn/operations/ccl/ccl_host_datastructures.hpp
  ttnn/cpp/ttnn/operations/ccl/erisc_datamover_builder.cpp
  ttnn/cpp/ttnn/operations/ccl/erisc_datamover_builder.hpp
Labels: cleanup, arch_name

#16244 Add support for DRAM Prefetcher op
  .github/workflows/tg-unit-tests-impl.yaml
  tech_reports/SubDevices/SubDevices.md
  tests/scripts/tg/run_tg_unit_tests.sh
  tests/tt_eager/python_api_testing/unit_testing/misc/test_matmul_1d_gather_in0.py
  tests/tt_metal/tt_metal/api/test_global_circular_buffers.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/10_dram_read_remote_cb_sync/test_dram_read_remote_cb.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/11_remote_cb_sync_matmul_single_core/test_remote_cb_sync_matmul.cpp
  tests/ttnn/unit_tests/operations/prefetcher_common.py
  tests/ttnn/unit_tests/operations/test_prefetcher.py
  tests/ttnn/unit_tests/operations/test_prefetcher_TG.py
  tests/ttnn/unit_tests/test_global_circular_buffer.py
  tt_metal/hw/inc/dataflow_api.h
  tt_metal/hw/inc/grayskull/dev_mem_map.h
  tt_metal/hw/inc/utils/utils.h
  tt_metal/impl/buffers/global_circular_buffer.cpp
  tt_metal/impl/buffers/global_circular_buffer.hpp
  tt_metal/impl/dispatch/kernels/cq_dispatch.cpp
  tt_metal/include/tt_metal/global_circular_buffer.hpp
  tt_metal/tt_metal.cpp
  tt_metal/tt_stl/reflection.hpp
  ttnn/CMakeLists.txt
  ttnn/cpp/pybind11/global_circular_buffer.cpp
  ttnn/cpp/pybind11/operations/__init__.hpp
  ttnn/cpp/ttnn/global_circular_buffer.cpp
  ttnn/cpp/ttnn/global_circular_buffer.hpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_matmul/device/all_gather_matmul_op.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_matmul/device/all_gather_matmul_op.hpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_matmul/device/multi_core/all_gather_matmul_op_multi_core.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/compute/bmm_large_block_zm_fused_bias_activation_gathered.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in0_ring_all_gather.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in1_ring_all_gather.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op.hpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_1d_program_factory.cpp
  ttnn/cpp/ttnn/operations/matmul/matmul.cpp
  ttnn/cpp/ttnn/operations/matmul/matmul.hpp
  ttnn/cpp/ttnn/operations/matmul/matmul_pybind.cpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/device/dram_prefetcher_op.cpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/device/dram_prefetcher_op.hpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/device/dram_prefetcher_op_multi_core.cpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/device/kernels/reader_dram.cpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/device/kernels/writer_l1.cpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/dram_prefetcher.cpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/dram_prefetcher.hpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/dram_prefetcher_pybind.cpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/dram_prefetcher_pybind.hpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher_pybind.cpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher_pybind.hpp
Labels: LLMs on Metal, llama3, llm_tg, tg-llama

#16602 Update METALIUM_GUIDE.md
  METALIUM_GUIDE.md
Labels: community

#16635 update build flag on programming examples docs
  tech_reports/prog_examples/add_2_integers_in_compute/Tutorial_Add_Two_Integers_in_a_Compute_Kernel.md
  tech_reports/prog_examples/add_2_integers_in_compute/add_2_integers_in_compute.md
  tech_reports/prog_examples/add_2_integers_in_riscv/Tutorial_Add_Two_Integers_in_a_Baby_RISC-V.md
  tech_reports/prog_examples/add_2_integers_in_riscv/add_2_integers_in_riscv.md
  tech_reports/prog_examples/dram_loopback/dram_loopback.md
  tech_reports/prog_examples/eltwise_binary/eltwise_binary.md
  tech_reports/prog_examples/eltwise_sfpu/eltwise_sfpu.md
  tech_reports/prog_examples/hello_world_compute/hello_world_compute.md
  tech_reports/prog_examples/hello_world_data_movement/hello_world_data_movement.md
  tech_reports/prog_examples/matmul_multi_core/matmul_multi_core.md
  tech_reports/prog_examples/matmul_multi_core_optimized/matmul_multi_core_optimized.md
  tech_reports/prog_examples/matmul_single_core/matmul_single_core.md
  tech_reports/prog_examples/pad_multi_core/pad_multi_core.md
  tech_reports/prog_examples/shard_data_rm/shard_data_rm.md
Labels: docs

#16749 #0: Disable BH tools test at workflow level
  .github/workflows/cpp-post-commit.yaml
Labels: infra-ci, ci-bug

#16823 [TT-Train] Add multidevice support to dropout
  tt-train/tests/core/n300_utils_test.cpp
  ttnn/cpp/ttnn/operations/experimental/dropout/dropout.cpp
Labels: TT-train

#16784 #16769: bring up all reduce async as a composite op and added llama shape ccl test sweep
  tests/ttnn/unit_tests/operations/ccl/test_all_reduce_async.py
  tests/ttnn/unit_tests/operations/ccl/test_ccl_async_TG_llama.py
  ttnn/cpp/ttnn/operations/experimental/ccl/CMakeLists.txt
  ttnn/cpp/ttnn/operations/experimental/ccl/all_reduce_async/all_reduce_async.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_reduce_async/all_reduce_async.hpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_reduce_async/all_reduce_async_pybind.cpp
  ttnn/cpp/ttnn/operations/experimental/ccl/all_reduce_async/all_reduce_async_pybind.hpp
  ttnn/cpp/ttnn/operations/experimental/ccl/ccl_experimental_pybind.cpp
Labels: op_cat: ccl

#16420 #16415: fix moreh_adam
  tests/ttnn/unit_tests/operations/test_moreh_adam.py
  ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_device_operation.cpp
  ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_program_factory.cpp
Labels: bug, moreh

#16771 [tt-train] Add gradient norm clipping
  tt-train/README.md
  tt-train/configs/training_shakespear_nanogpt.yaml
  tt-train/sources/examples/nano_gpt/main.cpp
  tt-train/sources/ttml/autograd/clip_gradient_norm.cpp
  tt-train/sources/ttml/autograd/clip_gradient_norm.hpp
  tt-train/sources/ttml/core/clip_grad_norm.cpp
  tt-train/sources/ttml/core/clip_grad_norm.hpp
  tt-train/sources/ttml/core/distributed/distributed.cpp
  tt-train/sources/ttml/core/distributed/distributed.hpp
  tt-train/sources/ttml/core/ttnn_all_includes.hpp
  tt-train/sources/ttml/optimizers/adamw.cpp
  tt-train/sources/ttml/optimizers/optimizer_base.cpp
  tt-train/sources/ttml/optimizers/optimizer_base.hpp
  tt-train/sources/ttml/optimizers/sgd.cpp
  tt-train/tests/autograd/clip_gradient_norm_test.cpp
  tt-train/tests/core/clip_grad_norm_test.cpp
Labels: TT-train

#16921 Create an API for running and measuring the runtime of a ttnn op chain for use during forge compilation
  tests/ttnn/unit_tests/gtests/CMakeLists.txt
  tests/ttnn/unit_tests/gtests/test_graph_query_op_runtime.cpp
  ttnn/cpp/ttnn/graph/graph_query_op_constraints.hpp
  ttnn/cpp/ttnn/graph/graph_query_op_runtime.hpp
  ttnn/cpp/ttnn/graph/graph_trace_utils.hpp
Labels: feature, forge

#16984 #0: Added custom tags for BH Post commit
  .github/workflows/blackhole-post-commit.yaml
Labels: blackhole

#16627 Add support for unpadded shapes in Matmul1D w/ gather_in0
  tests/tt_eager/python_api_testing/unit_testing/misc/test_matmul_1d_gather_in0.py
  tests/ttnn/unit_tests/operations/prefetcher_common.py
  tests/ttnn/unit_tests/operations/test_prefetcher.py
  tests/ttnn/unit_tests/operations/test_prefetcher_TG.py
  ttnn/cpp/ttnn/operations/matmul/device/kernels/compute/bmm_large_block_zm_fused_bias_activation_gathered.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in0_ring_all_gather.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_1d_program_factory.cpp
  ttnn/cpp/ttnn/operations/prefetcher/prefetcher/device/dram_prefetcher_op.cpp
Labels: metal

#17185 Remove ARCH_NAME references in prog_examples
  tech_reports/prog_examples/add_2_integers_in_compute/Tutorial_Add_Two_Integers_in_a_Compute_Kernel.md
  tech_reports/prog_examples/add_2_integers_in_compute/add_2_integers_in_compute.md
  tech_reports/prog_examples/add_2_integers_in_riscv/Tutorial_Add_Two_Integers_in_a_Baby_RISC-V.md
  tech_reports/prog_examples/add_2_integers_in_riscv/add_2_integers_in_riscv.md
  tech_reports/prog_examples/dram_loopback/dram_loopback.md
  tech_reports/prog_examples/eltwise_binary/eltwise_binary.md
  tech_reports/prog_examples/hello_world_compute/hello_world_compute.md
  tech_reports/prog_examples/hello_world_data_movement/hello_world_data_movement.md
  tech_reports/prog_examples/matmul_multi_core/matmul_multi_core.md
  tech_reports/prog_examples/matmul_multi_core_optimized/matmul_multi_core_optimized.md
  tech_reports/prog_examples/matmul_single_core/matmul_single_core.md
  tech_reports/prog_examples/pad_multi_core/pad_multi_core.md
  tech_reports/prog_examples/shard_data_rm/shard_data_rm.md
Labels: docs

#17000 Format broken Kernel APIs Tables
  tt_metal/hw/inc/dataflow_api.h
  tt_metal/include/compute_kernel_api.h
  tt_metal/include/compute_kernel_api/add_int32_sfpu.h
  tt_metal/include/compute_kernel_api/bcast.h
  tt_metal/include/compute_kernel_api/binary_bitwise_sfpu.h
  tt_metal/include/compute_kernel_api/binary_shift.h
  tt_metal/include/compute_kernel_api/cb_api.h
  tt_metal/include/compute_kernel_api/common.h
  tt_metal/include/compute_kernel_api/cumsum.h
  tt_metal/include/compute_kernel_api/eltwise_binary.h
  tt_metal/include/compute_kernel_api/eltwise_binary_sfpu.h
  tt_metal/include/compute_kernel_api/eltwise_unary/binop_with_scalar.h
  tt_metal/include/compute_kernel_api/eltwise_unary/bitwise_and.h
  tt_metal/include/compute_kernel_api/eltwise_unary/bitwise_not.h
  tt_metal/include/compute_kernel_api/eltwise_unary/bitwise_or.h
  tt_metal/include/compute_kernel_api/eltwise_unary/bitwise_xor.h
  tt_metal/include/compute_kernel_api/eltwise_unary/ceil.h
  tt_metal/include/compute_kernel_api/eltwise_unary/dropout.h
  tt_metal/include/compute_kernel_api/eltwise_unary/elu.h
  tt_metal/include/compute_kernel_api/eltwise_unary/erf_erfc.h
  tt_metal/include/compute_kernel_api/eltwise_unary/erfinv.h
  tt_metal/include/compute_kernel_api/eltwise_unary/exp.h
  tt_metal/include/compute_kernel_api/eltwise_unary/fill.h
  tt_metal/include/compute_kernel_api/eltwise_unary/floor.h
  tt_metal/include/compute_kernel_api/eltwise_unary/fmod.h
  tt_metal/include/compute_kernel_api/eltwise_unary/gelu.h
  tt_metal/include/compute_kernel_api/eltwise_unary/i0.h
  tt_metal/include/compute_kernel_api/eltwise_unary/i1.h
  tt_metal/include/compute_kernel_api/eltwise_unary/identity.h
  tt_metal/include/compute_kernel_api/eltwise_unary/isinf_isnan.h
  tt_metal/include/compute_kernel_api/eltwise_unary/left_shift.h
  tt_metal/include/compute_kernel_api/eltwise_unary/logical_not_noti.h
  tt_metal/include/compute_kernel_api/eltwise_unary/negative.h
  tt_metal/include/compute_kernel_api/eltwise_unary/prelu.h
  tt_metal/include/compute_kernel_api/eltwise_unary/rand.h
  tt_metal/include/compute_kernel_api/eltwise_unary/recip.h
  tt_metal/include/compute_kernel_api/eltwise_unary/relu.h
  tt_metal/include/compute_kernel_api/eltwise_unary/remainder.h
  tt_metal/include/compute_kernel_api/eltwise_unary/reverseops.h
  tt_metal/include/compute_kernel_api/eltwise_unary/right_shift.h
  tt_metal/include/compute_kernel_api/eltwise_unary/softplus.h
  tt_metal/include/compute_kernel_api/eltwise_unary/sqrt.h
  tt_metal/include/compute_kernel_api/eltwise_unary/trigonometry.h
  tt_metal/include/compute_kernel_api/eltwise_unary/typecast.h
  tt_metal/include/compute_kernel_api/mask.h
  tt_metal/include/compute_kernel_api/matmul.h
  tt_metal/include/compute_kernel_api/pack.h
  tt_metal/include/compute_kernel_api/reduce.h
  tt_metal/include/compute_kernel_api/reshuffle.h
  tt_metal/include/compute_kernel_api/tile_move_copy.h
  tt_metal/include/compute_kernel_api/tilize.h
  tt_metal/include/compute_kernel_api/transpose_wh.h
  tt_metal/include/compute_kernel_api/transpose_wh_dest.h
Labels: bug, docs, community

#17298 Privatize dprint_server.hpp
  tests/tt_metal/tt_metal/debug_tools/debug_tools_fixture.hpp
  tests/tt_metal/tt_metal/debug_tools/dprint/test_mute_print_server.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/noc/test_noc_unicast_vs_multicast_to_single_core_latency.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/old/matmul/matmul_global_l1.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/old/matmul/matmul_local_l1.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/old/noc/test_noc_read_global_l1.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/old/noc/test_noc_read_local_l1.cpp
  tests/tt_metal/tt_metal/test_compile_args.cpp
  tests/tt_metal/tt_metal/test_interleaved_layouts.cpp
  tt_metal/api/tt-metalium/device_pool.hpp
  tt_metal/impl/CMakeLists.txt
  tt_metal/impl/debug/dprint_server.hpp
  tt_metal/impl/device/device.cpp
  tt_metal/impl/device/device_pool.cpp
  tt_metal/impl/dispatch/command_queue.cpp
  tt_metal/impl/dispatch/hardware_command_queue.cpp
  tt_metal/impl/dispatch/kernel_config/fd_kernel.cpp
  tt_metal/impl/program/program.cpp
  tt_metal/llrt/rtoptions.cpp
  tt_metal/tools/profiler/CMakeLists.txt
  tt_metal/tools/profiler/tt_metal_profiler.cpp
  tt_metal/tt_metal.cpp
Labels: cleanup
