Repository tenstorrent/tt-metal, pull requests merged in 2025-08, with the labels that each got.

#25902 Optimize nd resharding op + Reenable DRAM nd resharding
  tests/tt_eager/python_api_testing/unit_testing/misc/test_nd_reshard.py
  ttnn/cpp/ttnn/operations/data_movement/sharded/reshard/device/kernels/nd_reshard_common.hpp
  ttnn/cpp/ttnn/operations/data_movement/sharded/reshard/device/kernels/nd_reshard_copy_local_shards.cpp
  ttnn/cpp/ttnn/operations/data_movement/sharded/reshard/device/kernels/nd_reshard_copy_pages_reader.cpp
  ttnn/cpp/ttnn/operations/data_movement/sharded/reshard/device/kernels/nd_reshard_copy_pages_writer.cpp
  ttnn/cpp/ttnn/operations/data_movement/sharded/reshard/device/nd_reshard_program_factory.cpp
Labels: nd sharding

#26029 MLA Meta-Layer Support
  models/demos/deepseek_v3/tests/test_mla_1d.py
  models/demos/deepseek_v3/tt/mla_1d.py
  models/demos/deepseek_v3/utils/config_dataclass.py
Labels: deepseekv3

#26123 Reapply "Replace truncating fp32->bf16 with tie-to-even rounding rule"
  tests/ttnn/unit_tests/operations/test_creation.py
  tests/ttnn/unit_tests/operations/test_full.py
  tt-train/tests/ops/layer_norm_op_test.cpp
  tt-train/tests/ops/rmsnorm_op_test.cpp
  tt-train/tests/ttnn_fixed/reduce_ops_test.cpp
  tt_metal/api/tt-metalium/bfloat16.hpp
  tt_metal/impl/data_format/bfloat16.cpp
  ttnn/cpp/ttnn/operations/eltwise/binary_ng/device/binary_ng_utils.cpp
  ttnn/cpp/ttnn/operations/full/device/full_program_factory.cpp
Labels: accuracy

#26140 Integrated page table with prefill MLA
  models/demos/deepseek_v3/tests/test_mla_1d.py
  models/demos/deepseek_v3/tt/mla_1d.py
  tests/tt_eager/python_api_testing/unit_testing/misc/test_deepseek_mla_ops.py
Labels: deepseekv3

#26313 Decoder layer (MLP) in decode mode works!!
  models/demos/deepseek_v3/reference/modeling_deepseek.py
  models/demos/deepseek_v3/tests/test_decoder_block.py
  models/demos/deepseek_v3/tests/test_lm_head.py
  models/demos/deepseek_v3/tests/test_mla_1d.py
  models/demos/deepseek_v3/tests/test_mlp_1d.py
  models/demos/deepseek_v3/tests/test_moe.py
  models/demos/deepseek_v3/tests/test_moe_experts.py
  models/demos/deepseek_v3/tests/test_moe_gate.py
  models/demos/deepseek_v3/tests/test_rms_norm.py
  models/demos/deepseek_v3/tt/decoder_block/decoder_block.py
  models/demos/deepseek_v3/tt/decoder_block/decoder_block_base.py
  models/demos/deepseek_v3/tt/decoder_block/moe_decoder_block.py
  models/demos/deepseek_v3/tt/decoder_layer.py
  models/demos/deepseek_v3/tt/mla_1d.py
  models/demos/deepseek_v3/tt/mlp/mlp_1d.py
  models/demos/deepseek_v3/tt/mlp/mlp_1d_dequant.py
  models/demos/deepseek_v3/tt/rms_norm/distributed_rms_norm.py
  models/demos/deepseek_v3/utils/config_dataclass.py
  models/demos/deepseek_v3/utils/config_helpers.py
  models/demos/deepseek_v3/utils/reference_forwards.py
  models/demos/deepseek_v3/utils/run_config.py
  models/demos/deepseek_v3/utils/test_utils.py
Labels: deepseekv3

#26347 Fix TensorAccessor Move/Copy ctor/assignment
  tt_metal/hw/inc/accessor/dspec.h
  tt_metal/hw/inc/accessor/tensor_accessor.h
Labels: nd sharding

#26053 Put the worker end point 2 first for the dram channel 1 in the soc desc of BH
  tt_metal/soc_descriptors/blackhole_140_arch.yaml
Labels: community

#27048 `tt_transformers`: Inference time memory reduction from `~180gb -> ~60gb` for `llama3-70b`.
  models/tt_transformers/tt/attention.py
  models/tt_transformers/tt/decoder.py
  models/tt_transformers/tt/embedding.py
  models/tt_transformers/tt/mlp.py
  models/tt_transformers/tt/multimodal/llama_cross_attention.py
  models/tt_transformers/tt/multimodal/llama_cross_attention_transformer_text.py
  models/tt_transformers/tt/multimodal/llama_cross_attention_transformer_vision.py
  models/tt_transformers/tt/multimodal/llama_cross_block.py
  models/tt_transformers/tt/multimodal/llama_image_attention.py
  models/tt_transformers/tt/multimodal/llama_image_block.py
  models/tt_transformers/tt/multimodal/llama_image_mlp.py
  models/tt_transformers/tt/multimodal/llama_image_transformer.py
  models/tt_transformers/tt/multimodal/llama_vision_encoder.py
  models/tt_transformers/tt/multimodal/llama_vision_model.py
Labels: models, llama3, TT-Transformers

#27074 Add attention sink support to FlashDecode
  tests/tt_eager/python_api_testing/unit_testing/misc/test_sdpa_decode_sink.py
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/kernels/compute/sdpa_flash_decode.cpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/kernels/dataflow/reader_decode_all.cpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/sdpa_decode_op.cpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/sdpa_decode_program_factory.cpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/sdpa_decode_program_factory.hpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/sdpa_decode.cpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/sdpa_decode.hpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/sdpa_decode_pybind.cpp
Labels: gpt-oss

#27145 #25975: Ported kernels in experimental OPs to TensorAccessor, part 1
  ttnn/cpp/ttnn/operations/experimental/bcast_to/device/bcast_to_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/bcast_to/device/kernels/dataflow/reader_interleaved_col_bcast_to.cpp
  ttnn/cpp/ttnn/operations/experimental/bcast_to/device/kernels/dataflow/reader_interleaved_no_bcast_to.cpp
  ttnn/cpp/ttnn/operations/experimental/bcast_to/device/kernels/dataflow/reader_interleaved_row_bcast_to.cpp
  ttnn/cpp/ttnn/operations/experimental/bcast_to/device/kernels/dataflow/reader_interleaved_scalar_bcast_to.cpp
  ttnn/cpp/ttnn/operations/experimental/bcast_to/device/kernels/dataflow/writer_interleaved_col_bcast_to.cpp
  ttnn/cpp/ttnn/operations/experimental/bcast_to/device/kernels/dataflow/writer_interleaved_no_bcast_to.cpp
  ttnn/cpp/ttnn/operations/experimental/bcast_to/device/kernels/dataflow/writer_interleaved_row_bcast_to.cpp
  ttnn/cpp/ttnn/operations/experimental/bcast_to/device/kernels/dataflow/writer_interleaved_scalar_bcast_to.cpp
  ttnn/cpp/ttnn/operations/experimental/dropout/device/dropout_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/dropout/device/kernels/dataflow/reader_dropout_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/dropout/device/kernels/dataflow/writer_dropout_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/padded_slice/device/kernels/dataflow/padded_slice_reader_rm_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/padded_slice/device/kernels/dataflow/padded_slice_reader_tiled_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/padded_slice/device/padded_slice_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/kernels/dataflow/reader_fill_cache_interleaved.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/kernels/dataflow/reader_paged_fused_update_cache_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/kernels/dataflow/reader_paged_row_major_fused_update_cache_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/kernels/dataflow/reader_update_cache_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/kernels/dataflow/writer_fill_cache_interleaved.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/kernels/dataflow/writer_paged_fused_update_cache_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/kernels/dataflow/writer_paged_row_major_fused_update_cache_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/kernels/dataflow/writer_update_cache_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/paged_fill_cache_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/paged_fused_update_cache_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/paged_update_cache_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/plusone/device/kernels/reader_plusone_interleaved.cpp
  ttnn/cpp/ttnn/operations/experimental/plusone/device/plusone_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/slice_write/device/kernels/dataflow/slice_write_reader_interleaved.cpp
  ttnn/cpp/ttnn/operations/experimental/slice_write/device/kernels/dataflow/slice_write_writer_interleaved.cpp
  ttnn/cpp/ttnn/operations/experimental/slice_write/device/slice_write_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/ssm/hc_sum_reduce/device/hc_sum_reduce_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/ssm/hc_sum_reduce/device/kernels/reader_ssm_1d_sum_reduce.cpp
  ttnn/cpp/ttnn/operations/experimental/ssm/hc_sum_reduce/device/kernels/writer_ssm_1d_sum_reduce.cpp
  ttnn/cpp/ttnn/operations/experimental/ssm/prefix_scan/device/prefix_scan_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/ssm/repeat_and_interleave_eltwise_mul/device/kernels/reader_ssm_eltwise_mul.cpp
  ttnn/cpp/ttnn/operations/experimental/ssm/repeat_and_interleave_eltwise_mul/device/kernels/writer_ssm_eltwise_mul.cpp
  ttnn/cpp/ttnn/operations/experimental/ssm/repeat_and_interleave_eltwise_mul/device/repeat_and_interleave_eltwise_mul_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/where/device/kernels/dataflow/elemwise_reader_kernel.cpp
  ttnn/cpp/ttnn/operations/experimental/where/device/kernels/dataflow/elemwise_reader_kernel_args.hpp
  ttnn/cpp/ttnn/operations/experimental/where/device/kernels/dataflow/elemwise_writer_kernel.cpp
  ttnn/cpp/ttnn/operations/experimental/where/device/kernels/dataflow/elemwise_writer_kernel_args.hpp
  ttnn/cpp/ttnn/operations/experimental/where/device/program_factory/element_wise_multi_core_where_program.cpp
Labels: made-by-ai

#27057 #25975: Refactor matmul kernels to use TensorAccessor
  tests/ttnn/unit_tests/gtests/test_generic_op.cpp
  tt_metal/impl/buffers/tensor_accessor_args.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_8bank_output_tiles_partitioned.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in0.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in0_sender_padding.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in1_receiver_writer_padding.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in1_ring_all_gather.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in1_sender_writer_padding.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_writer_bmm_tile_layout_in1.cpp
  ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/writer_bmm_tile_layout.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_program_factory.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_1d_program_factory.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_2d_program_factory.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_optimized_program_factory.cpp
  ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_program_factory.cpp
Labels: made-by-ai

#27209 #25975: Refactor experimental OPs to TensorAccessor, part 2
  ttnn/cpp/ttnn/operations/experimental/conv3d/device/conv3d_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/conv3d/device/kernels/reader_vol2col.cpp
  ttnn/cpp/ttnn/operations/experimental/conv3d/device/kernels/writer.cpp
  ttnn/cpp/ttnn/operations/experimental/matmul/attn_matmul/device/attn_matmul_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/matmul/attn_matmul/device/kernels/dataflow/reader_transformer_attn_matmul.cpp
  ttnn/cpp/ttnn/operations/experimental/matmul/group_attn_matmul/device/group_attn_matmul_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/matmul/group_attn_matmul/device/kernels/dataflow/reader_mcast_transformer_group_attn_matmul.cpp
  ttnn/cpp/ttnn/operations/experimental/matmul/group_attn_matmul/device/kernels/dataflow/writer_transformer_group_attn_matmul.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/all_reduce_create_qkv_heads/device/all_reduce_create_qkv_heads_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/all_reduce_create_qkv_heads/device/kernels/dataflow/reduction_receiver.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/concatenate_heads/device/concatenate_heads_program_factory.hpp
  ttnn/cpp/ttnn/operations/experimental/transformer/concatenate_heads/device/kernels/dataflow/reader_tm_tile_layout_concat_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/concatenate_heads/device/kernels/dataflow/writer_tm_tile_layout_concat_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads/device/kernels/dataflow/reader_tm_tile_layout_nlp_concat_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads/device/nlp_concat_heads_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_boltz/device/kernels/dataflow/reader_tm_tile_layout_nlp_concat_heads_boltz.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads_boltz/device/nlp_concat_heads_boltz_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads/device/kernels/dataflow/reader_tm_tile_layout_nlp_create_qkv_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads/device/kernels/dataflow/writer_tm_tile_layout_nlp_create_qkv_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads/device/nlp_create_qkv_heads_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_boltz/device/kernels/dataflow/reader_tm_tile_layout_nlp_create_qkv_heads_boltz.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_boltz/device/kernels/dataflow/writer_tm_tile_layout_nlp_create_qkv_heads_boltz.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_boltz/device/nlp_create_qkv_heads_boltz_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_decode/device/kernels/reader_interleaved_tm_tile_layout_nlp_create_qkv_heads_decode.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_decode/device/kernels/reader_tm_tile_layout_nlp_create_qkv_heads_decode.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_decode/device/kernels/reader_tm_tile_layout_nlp_create_qkv_heads_decode_on_subcoregrids.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_decode/device/nlp_create_qkv_heads_decode_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_falcon7b/device/kernels/dataflow/writer_tm_tile_layout_nlp_create_qkv_heads_falcon7b.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_falcon7b/device/nlp_create_qkv_heads_falcon7b_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_segformer/device/kernels/dataflow/reader_tm_tile_layout_nlp_create_qkv_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_segformer/device/kernels/dataflow/writer_tm_tile_layout_nlp_create_qkv_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_segformer/device/nlp_create_qkv_heads_segformer_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_vit/device/kernels/dataflow/reader_tm_tile_layout_nlp_create_qkv_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_vit/device/kernels/dataflow/writer_tm_tile_layout_nlp_create_qkv_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_vit/device/nlp_create_qkv_heads_vit_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_kv_cache_load_slice/device/kernels/dataflow/reader_unary_unpad_dims_interleaved_start_id_shard_optimized.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_kv_cache_load_slice/device/nlp_kv_cache_load_slice_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding/device/kernels/dataflow/reader_rotary_embedding_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding/device/kernels/dataflow/reader_rotary_embedding_interleaved_start_id_sharded.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding/device/kernels/dataflow/writer_rotary_embedding_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding/device/rotary_embedding_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/device/kernels/dataflow/reader_rotary_embedding_llama_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/device/kernels/dataflow/writer_rotary_embedding_llama_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/device/rotary_embedding_llama_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotate_half/device/kernels/dataflow/reader_rotate_half_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotate_half/device/kernels/dataflow/writer_rotate_half_interleaved_start_id.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/rotate_half/device/single_core/rotate_half_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/split_query_key_value_and_split_heads/device/kernels/dataflow/reader_tm_tile_layout_create_qkv_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/split_query_key_value_and_split_heads/device/kernels/dataflow/writer_tm_tile_layout_create_qkv_heads.cpp
  ttnn/cpp/ttnn/operations/experimental/transformer/split_query_key_value_and_split_heads/device/split_query_key_value_and_split_heads_program_factory.hpp
Labels: made-by-ai

#27401 #25975: Port all tt-train OPs to TensorAccessor
  tt-train/sources/ttml/metal/ops/cross_entropy_bw/device/cross_entropy_bw_program_factory.cpp
  tt-train/sources/ttml/metal/ops/cross_entropy_bw/device/kernels/dataflow/reader_cross_entropy_bw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/cross_entropy_bw/device/kernels/dataflow/writer_cross_entropy_bw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/cross_entropy_fw/device/cross_entropy_fw_program_factory.cpp
  tt-train/sources/ttml/metal/ops/cross_entropy_fw/device/kernels/dataflow/reader_cross_entropy_fw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/cross_entropy_fw/device/kernels/dataflow/writer_cross_entropy_fw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/profiler_no_op/device/kernels/dataflow/reader_profiler_no_op_interleaved_id.cpp
  tt-train/sources/ttml/metal/ops/profiler_no_op/device/kernels/dataflow/writer_profiler_no_op_interleaved_id.cpp
  tt-train/sources/ttml/metal/ops/profiler_no_op/device/profiler_no_op_program_factory.cpp
  tt-train/sources/ttml/metal/ops/rmsnorm_bw/device/kernels/dataflow/reader_rmsnorm_bw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/rmsnorm_bw/device/kernels/dataflow/writer_rmsnorm_bw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/rmsnorm_bw/device/rmsnorm_bw_program_factory.cpp
  tt-train/sources/ttml/metal/ops/rmsnorm_fw/device/kernels/dataflow/reader_rmsnorm_fw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/rmsnorm_fw/device/kernels/dataflow/writer_rmsnorm_fw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/rmsnorm_fw/device/rmsnorm_fw_program_factory.cpp
  tt-train/sources/ttml/metal/ops/silu_bw/device/kernels/dataflow/reader_silu_bw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/silu_bw/device/kernels/dataflow/writer_silu_bw_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/silu_bw/device/silu_bw_program_factory.cpp
  tt-train/sources/ttml/metal/ops/softmax/device/kernels/dataflow/reader_softmax_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/softmax/device/kernels/dataflow/writer_softmax_interleaved_start_id.cpp
  tt-train/sources/ttml/metal/ops/softmax/device/softmax_program_factory.cpp
Labels: made-by-ai
