Repository tenstorrent/tt-metal, pull requests merged in 2025-06, with the labels that each got.

#23024 SDXL: conv test update
  tests/ttnn/nightly/unit_tests/operations/conv/test_conv2d.py
Labels: Shield

#23185 SDXL: conv optimizations
  models/experimental/stable_diffusion_xl_base/demo/demo.py
  models/experimental/stable_diffusion_xl_base/tests/pcc/test_module_tt_crossattndownblock2d.py
  models/experimental/stable_diffusion_xl_base/tests/pcc/test_module_tt_crossattnmidblock2d.py
  models/experimental/stable_diffusion_xl_base/tests/pcc/test_module_tt_crossattnupblock.py
  models/experimental/stable_diffusion_xl_base/tests/pcc/test_module_tt_downblock2d.py
  models/experimental/stable_diffusion_xl_base/tests/pcc/test_module_tt_downsample2d.py
  models/experimental/stable_diffusion_xl_base/tests/pcc/test_module_tt_resnetblock2d.py
  models/experimental/stable_diffusion_xl_base/tests/pcc/test_module_tt_unet.py
  models/experimental/stable_diffusion_xl_base/tests/pcc/test_module_tt_upblock2d.py
  models/experimental/stable_diffusion_xl_base/tests/pcc/test_module_tt_upsample2d.py
  models/experimental/stable_diffusion_xl_base/tt/model_configs.py
  models/experimental/stable_diffusion_xl_base/tt/sdxl_utility.py
  models/experimental/stable_diffusion_xl_base/tt/tt_downsample2d.py
  models/experimental/stable_diffusion_xl_base/tt/tt_resnetblock2d.py
  models/experimental/stable_diffusion_xl_base/tt/tt_unet.py
  models/experimental/stable_diffusion_xl_base/tt/tt_upblock2d.py
  models/experimental/stable_diffusion_xl_base/tt/tt_upsample2d.py
  tests/ttnn/nightly/unit_tests/operations/conv/test_conv2d.py
Labels: Shield

#23027 Add operation accuracy measurement alternatives to `assert_with_pcc()`
  models/utility_functions.py
  tests/ttnn/utils_for_testing.py
Labels: accuracy

#23257 SDXL: GroupNorm update
  models/experimental/stable_diffusion_xl_base/tt/tt_resnetblock2d.py
  tests/ttnn/unit_tests/operations/fused/test_group_norm.py
  tests/ttnn/unit_tests/operations/fused/test_group_norm_DRAM.py
Labels: SDXL, Shield

#22691 [Blackhole] Remove default template arguments and explicitly forward DST_ACCUM_MODE
  tests/tt_metal/tt_metal/test_kernels/compute/unpack_tilizeA_B.cpp
  tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_math_binary_api.h
  tt_metal/include/compute_kernel_api/bcast.h
  tt_metal/include/compute_kernel_api/eltwise_binary.h
Labels: community

#23025 Reduce L1 small by implementing reader indices segments
  models/experimental/functional_unet/tests/test_unet_perf.py
  ttnn/cpp/ttnn/operations/conv/conv2d/device/conv2d_op_sharded_program_factory.cpp
  ttnn/cpp/ttnn/operations/conv/conv2d/device/conv2d_op_width_sharded_program_factory.cpp
  ttnn/cpp/ttnn/operations/conv/conv2d/device/kernels/activation_reader_width_sharded.cpp
  ttnn/cpp/ttnn/operations/conv/conv2d/device/kernels/height_sharded_reader_common.hpp
  ttnn/cpp/ttnn/operations/conv/conv2d/device/kernels/reader_conv_activations_2d_mcast_padded_with_halo_3x3_weights_v2.cpp
  ttnn/cpp/ttnn/operations/conv/conv2d/device/kernels/reader_conv_activations_padded_with_halo_3x3_weights_v2.cpp
  ttnn/cpp/ttnn/operations/conv/conv2d/device/kernels/reader_depthwise_conv1d.cpp
  ttnn/cpp/ttnn/operations/conv/conv2d/device/kernels/reader_writer_tiled_out_1d_mcast_receiver_conv_weights_tiled_col_to_rm_blocks.cpp
  ttnn/cpp/ttnn/operations/conv/conv2d/device/kernels/reader_writer_tiled_out_1d_mcast_sender_conv_weights_tiled_col_to_rm_blocks.cpp
  ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded.cpp
  ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_large_kernel_v2.cpp
  ttnn/cpp/ttnn/operations/pool/generic/device/pool_multi_core_program_factory.cpp
  ttnn/cpp/ttnn/operations/sliding_window/sliding_window.cpp
  ttnn/cpp/ttnn/operations/sliding_window/sliding_window.hpp
Labels: op_cat: conv2D, SDXL

#23118 Add multicore implementation of `ttnn.experimental.cumsum()`
  tests/ttnn/unit_tests/operations/reduce/test_cumsum.py
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/cumsum.cpp
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/cumsum.hpp
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/cumsum_pybind.hpp
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/device/cumsum_device_operation.cpp
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/device/cumsum_device_operation.hpp
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/device/cumsum_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/device/kernels/compute/cumsum_compute.cpp
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/device/kernels/dataflow/cumsum_common.hpp
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/device/kernels/dataflow/cumsum_reader.cpp
  ttnn/cpp/ttnn/operations/experimental/reduction/cumsum/device/kernels/dataflow/cumsum_writer.cpp
Labels: op_cat: reduces

#22929 ND sharding CRTA
  tech_reports/nd_sharding/sharded_accessor.md
  tests/ttnn/benchmark/python/test_accessor_benchmarks.py
  tests/ttnn/unit_tests/gtests/accessor/kernels/accessor_benchmark.cpp
  tests/ttnn/unit_tests/gtests/accessor/kernels/accessor_constructor_benchmark.cpp
  tests/ttnn/unit_tests/gtests/accessor/kernels/accessor_get_noc_addr_page_id_benchmark.cpp
  tests/ttnn/unit_tests/gtests/accessor/kernels/reader_reshard.cpp
  tests/ttnn/unit_tests/gtests/accessor/kernels/writer_reshard.cpp
  tests/ttnn/unit_tests/gtests/accessor/test_accessor_benchmarks.cpp
  tests/ttnn/unit_tests/gtests/accessor/test_sharded_accessor.cpp
  tests/ttnn/unit_tests/gtests/accessor/test_sharded_accessor_on_device.cpp
  tt_metal/hostdevcommon/api/hostdevcommon/flags.hpp
  tt_metal/hostdevcommon/api/hostdevcommon/sharded_accessor/arg_config.hpp
  tt_metal/hw/inc/accessor/detail.h
  tt_metal/hw/inc/accessor/detail/args_location.hpp
  tt_metal/hw/inc/accessor/detail/array_wrapper.hpp
  tt_metal/hw/inc/accessor/detail/const.hpp
  tt_metal/hw/inc/accessor/detail/dspec.h
  tt_metal/hw/inc/accessor/detail/helpers.hpp
  tt_metal/hw/inc/accessor/sharded_accessor.h
  ttnn/cpp/ttnn/operations/sharding_utilities.cpp
  ttnn/cpp/ttnn/operations/sharding_utilities.hpp
Labels: ttnn

#24281 Configure 6U CI pipelines to run nightly
  .github/workflows/galaxy-frequent-tests.yaml
  .github/workflows/galaxy-model-perf-tests.yaml
  .github/workflows/galaxy-nightly-tests.yaml
  .github/workflows/galaxy-unit-tests.yaml
Labels: LLMs on Metal, llama3, tg-llama

#24258 #24267: Universal TensorAccessor for kernels, which can handle 2D sharded, ND sharded, and interleaved tensors
  tech_reports/nd_sharding/sharded_accessor.md
  tech_reports/tensor_accessor/tensor_accessor.md
  tests/ttnn/unit_tests/gtests/CMakeLists.txt
  tests/ttnn/unit_tests/gtests/accessor/kernels/accessor_constructor_benchmark.cpp
  tests/ttnn/unit_tests/gtests/accessor/kernels/accessor_get_noc_addr_page_id_benchmark.cpp
  tests/ttnn/unit_tests/gtests/accessor/kernels/reader_reshard.cpp
  tests/ttnn/unit_tests/gtests/accessor/kernels/writer_reshard.cpp
  tests/ttnn/unit_tests/gtests/accessor/test_accessor_benchmarks.cpp
  tests/ttnn/unit_tests/gtests/accessor/test_sharded_accessor_on_device.cpp
  tests/ttnn/unit_tests/gtests/accessor/test_tensor_accessor.cpp
  tests/ttnn/unit_tests/gtests/accessor/test_tensor_accessor_on_device.cpp
  tt_metal/hostdevcommon/api/hostdevcommon/flags.hpp
  tt_metal/hostdevcommon/api/hostdevcommon/sharded_accessor/arg_config.hpp
  tt_metal/hostdevcommon/api/hostdevcommon/tensor_accessor/arg_config.hpp
  tt_metal/hw/inc/accessor/args_location.h
  tt_metal/hw/inc/accessor/array_wrapper.h
  tt_metal/hw/inc/accessor/const.h
  tt_metal/hw/inc/accessor/detail/const.hpp
  tt_metal/hw/inc/accessor/dspec.h
  tt_metal/hw/inc/accessor/helpers.h
  tt_metal/hw/inc/accessor/tensor_accessor.h
  ttnn/CMakeLists.txt
  ttnn/api/ttnn/tensor/tensor_accessor_args.hpp
  ttnn/core/tensor/tensor_accessor_args.cpp
  ttnn/cpp/ttnn/operations/sharding_utilities.cpp
  ttnn/cpp/ttnn/operations/sharding_utilities.hpp
Labels: nd sharding
