Repository tenstorrent/tt-metal, pull requests merged in 2025-02, with the labels that each got.

#17509 update deprecated API use
  tt_metal/kernels/compute/eltwise_sfpu.cpp
Labels: cleanup

#17507 Add test for create_qkv_heads_decode on subcoregrids
  tests/tt_eager/python_api_testing/unit_testing/misc/test_nlp_create_qkv_heads_decode.py
  ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_decode/device/nlp_create_qkv_heads_decode_program_factory.cpp
Labels: LLMs on Metal, tg-llama

#17424 #0: Use kernel time instead of fw time for calculating device time
  models/perf/perf_report.py
Labels: LLMs on Metal

#17666 #17623: Delete artifact when one of the steps fails.
  .github/workflows/docs-latest-public.yaml
Labels: ci-bug

#17794 Add Mistral-Small-24B-Instruct-2501 support
  models/demos/llama3/PERF.md
  models/demos/llama3/tests/reference_outputs/Mistral-Small-24B-Instruct-2501.refpt
  models/demos/llama3/tt/llama_attention.py
  models/demos/llama3/tt/model_config.py
Labels: llama3

#17856 Create workflow to mirror a branch from fork
  .github/workflows/mirror-fork-branch.yaml
Labels: P2, feature

#16753 Refactor llama3 demo to the new generator API
  models/demos/llama3/PERF.md
  models/demos/llama3/README.md
  models/demos/llama3/demo/conftest.py
  models/demos/llama3/demo/demo.py
  models/demos/llama3/demo/input_data_questions.json
  models/demos/llama3/demo/sample_prompts/input_data_long_128k.json
  models/demos/llama3/demo/sample_prompts/input_data_long_16k.json
  models/demos/llama3/demo/sample_prompts/input_data_long_1k.json
  models/demos/llama3/demo/sample_prompts/input_data_long_2k.json
  models/demos/llama3/demo/sample_prompts/input_data_long_32k.json
  models/demos/llama3/demo/sample_prompts/input_data_long_4k.json
  models/demos/llama3/demo/sample_prompts/input_data_long_64k.json
  models/demos/llama3/demo/sample_prompts/input_data_long_8k.json
  models/demos/llama3/demo/sample_prompts/input_data_prefill_128.json
  models/demos/llama3/demo/sample_prompts/input_data_questions_prefill_128.json
  models/demos/llama3/demo/sample_prompts/input_data_questions_prefill_256.json
  models/demos/llama3/demo/simple_text_demo.py
  models/demos/llama3/demo/simple_vision_demo.py
  models/demos/llama3/lt
  models/demos/llama3/tests/multimodal/test_llama_cross_attention_transformer_text.py
  models/demos/llama3/tests/test_llama_accuracy.py
  models/demos/llama3/tests/test_llama_attention_prefill.py
  models/demos/llama3/tests/test_llama_chunked_generation.py
  models/demos/llama3/tests/test_llama_decoder_prefill.py
  models/demos/llama3/tests/test_llama_model.py
  models/demos/llama3/tests/test_llama_model_prefill.py
  models/demos/llama3/tt/generator.py
  models/demos/llama3/tt/llama_common.py
  models/demos/llama3/tt/llama_model.py
  models/demos/llama3/tt/llama_rope.py
  models/demos/llama3/tt/model_config.py
  models/demos/llama3/tt/multimodal/llama_cross_attention_transformer_vision.py
  models/demos/llama3/tt/multimodal/llama_image_mlp.py
  models/demos/llama3/tt/multimodal/llama_vision_model.py
  tests/scripts/single_card/run_single_card_demo_tests.sh
  tests/scripts/t3000/run_t3000_demo_tests.sh
  tests/scripts/t3000/run_t3000_frequent_tests.sh
  tests/scripts/t3000/run_t3000_unit_tests.sh
  tests/scripts/tg/run_tg_demo_tests.sh
  tests/tt_eager/python_api_testing/unit_testing/misc/test_rotary_embedding_llama.py
  tests/tt_eager/python_api_testing/unit_testing/misc/test_rotary_embedding_llama_fused_qk.py
  tt_metal/python_env/requirements-dev.txt
Labels: llama3

#18116 #18115: Remove running grayskull tests in post-commit
  .github/workflows/_test-wheels-impl.yaml
  .github/workflows/all-post-commit-workflows.yaml
  .github/workflows/fast-dispatch-full-regressions-and-models-impl.yaml
  .github/workflows/full-regressions-and-models.yaml
  .github/workflows/metal-run-microbenchmarks.yaml
  .github/workflows/models-post-commit-wrapper.yaml
  .github/workflows/models-post-commit.yaml
  .github/workflows/perf-models-impl.yaml
  .github/workflows/run-profiler-regression-wrapper.yaml
  .github/workflows/run-profiler-regression.yaml
  .github/workflows/stress-fast-dispatch-build-and-unit-tests.yaml
  .github/workflows/stress-slow-dispatch-build-and-unit-tests.yaml
  .github/workflows/test-dispatch.yaml
  .github/workflows/tt-metal-l2-nightly.yaml
  .github/workflows/ttnn-post-commit-wrapper.yaml
  .github/workflows/ttnn-post-commit.yaml
  .github/workflows/ttnn-run-sweeps.yaml
  .github/workflows/umd-unit-tests-wrapper.yaml
  .github/workflows/umd-unit-tests.yaml
Labels: infra-ci

#18053 fix sliding window hash calculus
  tests/ttnn/unit_tests/gtests/CMakeLists.txt
  tests/ttnn/unit_tests/gtests/test_sliding_window_infra.cpp
  ttnn/cpp/ttnn/operations/sliding_window/sliding_window.cpp
Labels: Fruit
