Repository tenstorrent/tt-metal, pull requests merged in 2025-07, with the labels that each got.

#23725 23706: cumprod cleanup
  docs/source/ttnn/ttnn/api.rst
  tests/ttnn/unit_tests/operations/reduce/test_cumprod.py
  tests/ttnn/unit_tests/operations/test_scatter.py
  tests/ttnn/unit_tests/operations/test_tosa_scatter.py
  ttnn/CMakeLists.txt
  ttnn/cpp/ttnn/operations/experimental/experimental_pybind.cpp
  ttnn/cpp/ttnn/operations/experimental/reduction/CMakeLists.txt
  ttnn/cpp/ttnn/operations/experimental/reduction/cumprod/cumprod_pybind.hpp
  ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/dataflow/reader_scatter.cpp
  ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/dataflow/writer_scatter.cpp
  ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/scatter_common.hpp
  ttnn/cpp/ttnn/operations/experimental/scatter/device/scatter_device_operation_types.hpp
  ttnn/cpp/ttnn/operations/experimental/scatter/device/scatter_program_factory.cpp
  ttnn/cpp/ttnn/operations/experimental/scatter/scatter.cpp
  ttnn/cpp/ttnn/operations/experimental/scatter/scatter_enums.hpp
  ttnn/cpp/ttnn/operations/experimental/scatter/tosa_scatter.cpp
  ttnn/cpp/ttnn/operations/reduction/CMakeLists.txt
  ttnn/cpp/ttnn/operations/reduction/cumprod/cumprod.cpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/cumprod.hpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/cumprod_pybind.cpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/cumprod_pybind.hpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/device/cumprod_device_operation.cpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/device/cumprod_device_operation.hpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/device/cumprod_program_factory.cpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/device/kernels/compute/cumprod_multicore.cpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/device/kernels/cumprod_common.hpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/device/kernels/dataflow/reader_multicore_cumprod.cpp
  ttnn/cpp/ttnn/operations/reduction/cumprod/device/kernels/dataflow/writer_multicore_cumprod.cpp
  ttnn/cpp/ttnn/operations/reduction/reduction_pybind.cpp
Labels: P2

#24440 Enable and start dev-hugepages\x2d1G.mount during configure_hugepages…
  install_dependencies.sh
Labels: install, dependencies

#24505 #24504: Avoid modifying core grid in NdShardSpec for representing block sharding
  tests/ttnn/unit_tests/gtests/tensor/test_tensor_nd_sharding.cpp
  tt_metal/api/tt-metalium/buffer_distribution_spec.hpp
  tt_metal/api/tt-metalium/buffer_types.hpp
  tt_metal/impl/buffers/buffer_distribution_spec.cpp
  ttnn/api/ttnn/tensor/types.hpp
  ttnn/core/tensor/layout/tensor_layout.cpp
  ttnn/core/tensor/tensor_spec.cpp
Labels: nd sharding

#23533 Make assert_with_ulp() robust to empty tensors, NaN and Inf values
  models/utility_functions.py
  tests/ttnn/utils_for_testing.py
Labels: accuracy

#24783 DeepSeekV3 MLA Module Bring-up Decode TP 8
  check_copyright_config.yaml
  models/demos/deepseek_v3/reference/deepseek/LICENSE-DeepSeek-V3
  models/demos/deepseek_v3/reference/deepseek/README.md
  models/demos/deepseek_v3/reference/deepseek/configs/config_671B.json
  models/demos/deepseek_v3/reference/deepseek/kernel.py
  models/demos/deepseek_v3/reference/deepseek/model.py
  models/demos/deepseek_v3/reference/deepseek/requirements.txt
  models/demos/deepseek_v3/reference/deepseek/rope_helpers.py
  models/demos/deepseek_v3/tests/test_mla_1d.py
  models/demos/deepseek_v3/tt/ccl_1d.py
  models/demos/deepseek_v3/tt/mla_1d.py
  models/demos/deepseek_v3/tt/rope.py
  models/demos/deepseek_v3/utils/config_dataclass.py
  models/utility_functions.py
  tests/tt_eager/python_api_testing/unit_testing/misc/test_deepseek_mla_ops.py
Labels: LLMs on Metal, llm_tg, deepseekv3

#24293 Speed up get noc addr up to 25%
  tests/ttnn/benchmark/python/test_accessor_benchmarks.py
  tests/ttnn/unit_tests/gtests/accessor/kernels/accessor_get_noc_addr_page_coord_benchmark.cpp
  tests/ttnn/unit_tests/gtests/accessor/test_accessor_benchmarks.cpp
  tt_metal/hw/inc/accessor/tensor_accessor.h
Labels: nd sharding

#25303 MLA Prefill TP=8 support
  models/demos/deepseek_v3/reference/deepseek/model.py
  models/demos/deepseek_v3/tests/test_mla_1d.py
  models/demos/deepseek_v3/tt/mla_1d.py
  ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/all_gather_async_op.cpp
Labels: deepseekv3

#25416 DP 8 SDPA support for MLA Decode
  models/demos/deepseek_v3/tests/test_mla_1d.py
  models/demos/deepseek_v3/tt/mla_1d.py
Labels: deepseekv3

#25436 `tt-transformers`: Fixed unnecessary model weights cast for `HF` models
  models/tt_transformers/README.md
  models/tt_transformers/demo/simple_vision_demo.py
  models/tt_transformers/tests/generate_reference_outputs.py
  models/tt_transformers/tests/test_accuracy.py
  models/tt_transformers/tests/test_attention.py
  models/tt_transformers/tests/test_attention_prefill.py
  models/tt_transformers/tests/test_chunked_generation.py
  models/tt_transformers/tests/test_decoder.py
  models/tt_transformers/tests/test_decoder_prefill.py
  models/tt_transformers/tests/test_embedding.py
  models/tt_transformers/tests/test_interleaved_to_sharded.py
  models/tt_transformers/tests/test_lm_head.py
  models/tt_transformers/tests/test_mlp.py
  models/tt_transformers/tests/test_model.py
  models/tt_transformers/tests/test_ref.py
  models/tt_transformers/tests/test_rms_norm.py
  models/tt_transformers/tests/test_torch.py
  models/tt_transformers/tt/model_config.py
Labels: bug, models, TT-Transformers

#25732 Adding paged support for FlashMLA decode
  tests/tt_eager/python_api_testing/unit_testing/misc/test_flash_multi_latent_attention_decode.py
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/kernels/dataflow/dataflow_common.hpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/kernels/dataflow/reader_decode_all.cpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/sdpa_decode_op.cpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/sdpa_decode.cpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/sdpa_decode.hpp
  ttnn/cpp/ttnn/operations/transformer/sdpa_decode/sdpa_decode_pybind.cpp
Labels: LLMs on Metal, deepseekv3

#25167 24616: scatter cleanup
  .github/workflows/ttnn-run-sweeps.yaml
  tests/sweep_framework/sweeps/eltwise/binary/scatter/scatter_forge.py
  tests/tt_eager/python_api_testing/sweep_tests/op_map.py
  tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_scatter.py
  tests/tt_eager/python_api_testing/sweep_tests/tt_lib_ops.py
  tests/ttnn/unit_tests/operations/eltwise/test_binary_composite.py
  tests/ttnn/unit_tests/operations/test_scatter.py
  tests/ttnn/unit_tests/operations/test_tosa_scatter.py
  ttnn/CMakeLists.txt
  ttnn/cpp/ttnn/operations/data_movement/CMakeLists.txt
  ttnn/cpp/ttnn/operations/data_movement/data_movement_pybind.cpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/device/kernels/dataflow/reader_scatter.cpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/device/kernels/dataflow/writer_scatter.cpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/device/kernels/scatter_common.hpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/device/scatter_device_operation.cpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/device/scatter_device_operation.hpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/device/scatter_device_operation_types.hpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/device/scatter_program_factory.cpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/device/scatter_program_factory.hpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/scatter.cpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/scatter.hpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/scatter_enums.hpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/scatter_pybind.cpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/scatter_pybind.hpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/tosa_scatter.cpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/tosa_scatter.hpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/tosa_scatter_pybind.cpp
  ttnn/cpp/ttnn/operations/data_movement/scatter/tosa_scatter_pybind.hpp
  ttnn/cpp/ttnn/operations/eltwise/binary/binary_composite.hpp
  ttnn/cpp/ttnn/operations/eltwise/binary/binary_pybind.cpp
  ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.cpp
  ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.hpp
  ttnn/cpp/ttnn/operations/experimental/experimental_pybind.cpp
  ttnn/cpp/ttnn/operations/experimental/scatter/CMakeLists.txt
  ttnn/cpp/ttnn/operations/experimental/scatter/tosa_scatter_pybind.hpp
  ttnn/ttnn/operations/binary.py
Labels: P2

#25755 Adding feature to selectively run paged cache op on subset of available mesh devices
  tests/ttnn/unit_tests/operations/test_paged_cache_mask.py
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/paged_cache_operation.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/device/paged_cache_operation.hpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/paged_cache.cpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/paged_cache.hpp
  ttnn/cpp/ttnn/operations/experimental/paged_cache/paged_cache_pybind.cpp
Labels: metal, deepseekv3

#25525 assert_with_ulp(): improve documentation and fix bfloat8_b results
  tests/ttnn/utils_for_testing.py
Labels: ttnn-unit-tests, accuracy

#25892 Refactor MLA1D
  models/demos/deepseek_v3/tt/mla_1d.py
Labels: deepseekv3

#25904 Use paged attention in MLA decode
  models/demos/deepseek_v3/tests/test_mla_1d.py
  models/demos/deepseek_v3/tt/mla_1d.py
Labels: deepseekv3

#25827 `llama3_subdevices/text_demo.py`: fixed broken `stop_at_eos` flag
  models/demos/llama3_subdevices/README.md
  models/demos/llama3_subdevices/demo/text_demo.py
Labels: bug, models, llama3

#25897 Fix non-determinism of pow function (disable stochastic rounding)
  tests/ttnn/unit_tests/operations/eltwise/test_pow.py
  tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_binary.h
Labels: LLK, op_cat: eltwise, accuracy
