Repository tenstorrent/tt-metal, pull requests merged in 2025-09, with the labels that each got.

#27488 Fix tensor accessor constructor perf regression
  tests/ttnn/benchmark/python/test_accessor_benchmarks.py
  tt_metal/hw/inc/accessor/dspec.h
  tt_metal/hw/inc/accessor/helpers.h
  tt_metal/hw/inc/accessor/tensor_accessor.h
Labels: nd sharding

#27294 Add option to dump profiler results early (without instance destruction)
  tests/scripts/run_profiler_regressions.sh
  tests/ttnn/benchmark/python/test_accessor_benchmarks.py
  tests/ttnn/unit_tests/gtests/accessor/test_accessor_benchmarks.cpp
  tt_metal/impl/profiler/profiler.hpp
  tt_metal/impl/profiler/tt_metal_profiler.cpp
  tt_metal/llrt/rtoptions.cpp
  tt_metal/llrt/rtoptions.hpp
  ttnn/tracy/__main__.py
Labels: feature

#27600 Fix variability in CI performance checks by removing per-iteration logging overhead
  models/tt_transformers/demo/simple_text_demo.py
  tests/scripts/t3000/run_t3000_demo_tests.sh
Labels: made-by-ai

#28171 Fix broken examples in tensor_sharding.md
  tech_reports/tensor_sharding/tensor_sharding.md
Labels: nd sharding

#28615 Make ULP formula handle input == dtype.max properly
  models/common/utility_functions.py
Labels: ttnn-unit-tests

#29328 [skip ci] Fix accessor benchmarks failing with watcher enabled
  tests/ttnn/unit_tests/gtests/accessor/kernels/accessor_get_noc_addr_page_id_benchmark.cpp
Labels: nd sharding

#29306 Add sci_mode and precision option to set_printoptions
  tests/ttnn/unit_tests/test_print_tensor.py
  ttnn/api/ttnn/core.hpp
  ttnn/api/ttnn/tensor/tensor_impl.hpp
  ttnn/core/core.cpp
  ttnn/core/tensor/tensor_impl.cpp
  ttnn/cpp/ttnn-pybind/core.cpp
Labels: ttnn, feature

#29495 Improve execution speed of new exp approximation ( + bump tt-sim version) (#26988)
  .github/workflows/ttsim.yaml
  tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_exp.h
  tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_exp.h
Labels: kernels, op_cat: eltwise
