Repository tenstorrent/tt-metal, pull requests merged in 2025-03, with the labels that each got.

#18570 #0: Remove ThreadManager from api
  tt_metal/api/tt-metalium/utils.hpp
Labels: cleanup

#18578 Fabric initialization infrastructure for fast dispatch
  tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/test_dispatcher.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/test_prefetcher.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/kernels/traffic_gen.hpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/kernels/traffic_gen_rx.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/kernels/traffic_gen_tx.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_mux_demux.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_mux_demux_2level.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_tx_rx.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_bi_tunnel_2ep.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_bi_tunnel_4ep.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_loopback_tunnel.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_mux_demux.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_uni_tunnel.cpp
  tt_metal/CMakeLists.txt
  tt_metal/api/tt-metalium/command_queue_interface.hpp
  tt_metal/api/tt-metalium/control_plane.hpp
  tt_metal/api/tt-metalium/device_pool.hpp
  tt_metal/api/tt-metalium/dispatch_core_common.hpp
  tt_metal/api/tt-metalium/fabric_host_interface.h
  tt_metal/api/tt-metalium/rtoptions.hpp
  tt_metal/fabric/CMakeLists.txt
  tt_metal/impl/CMakeLists.txt
  tt_metal/impl/device/device.cpp
  tt_metal/impl/device/device_pool.cpp
  tt_metal/impl/dispatch/kernel_config/demux.cpp
  tt_metal/impl/dispatch/kernel_config/demux.hpp
  tt_metal/impl/dispatch/kernel_config/dispatch.cpp
  tt_metal/impl/dispatch/kernel_config/dispatch.hpp
  tt_metal/impl/dispatch/kernel_config/eth_router.cpp
  tt_metal/impl/dispatch/kernel_config/eth_router.hpp
  tt_metal/impl/dispatch/kernel_config/eth_tunneler.cpp
  tt_metal/impl/dispatch/kernel_config/eth_tunneler.hpp
  tt_metal/impl/dispatch/kernel_config/fabric_router_vc.cpp
  tt_metal/impl/dispatch/kernel_config/fabric_router_vc.hpp
  tt_metal/impl/dispatch/kernel_config/fd_kernel.cpp
  tt_metal/impl/dispatch/kernel_config/fd_kernel.hpp
  tt_metal/impl/dispatch/kernel_config/mux.cpp
  tt_metal/impl/dispatch/kernel_config/mux.hpp
  tt_metal/impl/dispatch/kernel_config/prefetch.cpp
  tt_metal/impl/dispatch/kernel_config/prefetch.hpp
  tt_metal/impl/dispatch/kernels/cq_dispatch.cpp
  tt_metal/impl/dispatch/kernels/cq_prefetch.cpp
  tt_metal/impl/dispatch/kernels/packet_demux.cpp
  tt_metal/impl/dispatch/kernels/packet_mux.cpp
  tt_metal/impl/dispatch/kernels/packet_queue.hpp
  tt_metal/impl/dispatch/kernels/packet_queue_ctrl.hpp
  tt_metal/impl/dispatch/kernels/vc_eth_tunneler.cpp
  tt_metal/impl/dispatch/kernels/vc_packet_router.cpp
  tt_metal/impl/dispatch/topology.cpp
  tt_metal/impl/dispatch/topology.hpp
  tt_metal/jit_build/build.cpp
  tt_metal/llrt/rtoptions.cpp
Labels: fast-dispatch

#18310 #0: portable build failure log
  tt_metal/jit_build/build.cpp
Labels: cleanup

#18333 Dump configuration registers
  tests/tt_metal/tt_metal/debug_tools/CMakeLists.txt
  tests/tt_metal/tt_metal/debug_tools/dprint/test_print_config_register.cpp
  tests/tt_metal/tt_metal/test_kernels/dataflow/writer_config_reg.cpp
  tt_metal/hw/inc/debug/dprint_tensix.h
  tt_metal/hw/inc/debug/dprint_tensix_pack.h
  tt_metal/hw/inc/debug/dprint_tensix_unpack.h
Labels: tensix_debug

#18723 #18726: Fabric initialization infrastructure for fast dispatch
  tests/tt_metal/tt_metal/dispatch/dispatch_util/test_dispatch_settings.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/test_dispatcher.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/test_prefetcher.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/kernels/traffic_gen.hpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/kernels/traffic_gen_rx.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/kernels/traffic_gen_tx.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_mux_demux.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_mux_demux_2level.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_tx_rx.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_bi_tunnel_2ep.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_bi_tunnel_4ep.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_loopback_tunnel.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_mux_demux.cpp
  tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_uni_tunnel.cpp
  tt_metal/CMakeLists.txt
  tt_metal/api/tt-metalium/command_queue_common.hpp
  tt_metal/api/tt-metalium/command_queue_interface.hpp
  tt_metal/api/tt-metalium/control_plane.hpp
  tt_metal/api/tt-metalium/device_pool.hpp
  tt_metal/api/tt-metalium/dispatch_core_common.hpp
  tt_metal/api/tt-metalium/fabric_host_interface.h
  tt_metal/api/tt-metalium/rtoptions.hpp
  tt_metal/fabric/CMakeLists.txt
  tt_metal/impl/CMakeLists.txt
  tt_metal/impl/device/device.cpp
  tt_metal/impl/device/device_pool.cpp
  tt_metal/impl/dispatch/dispatch_mem_map.cpp
  tt_metal/impl/dispatch/kernel_config/demux.cpp
  tt_metal/impl/dispatch/kernel_config/demux.hpp
  tt_metal/impl/dispatch/kernel_config/dispatch.cpp
  tt_metal/impl/dispatch/kernel_config/dispatch.hpp
  tt_metal/impl/dispatch/kernel_config/eth_router.cpp
  tt_metal/impl/dispatch/kernel_config/eth_router.hpp
  tt_metal/impl/dispatch/kernel_config/eth_tunneler.cpp
  tt_metal/impl/dispatch/kernel_config/eth_tunneler.hpp
  tt_metal/impl/dispatch/kernel_config/fabric_router_vc.cpp
  tt_metal/impl/dispatch/kernel_config/fabric_router_vc.hpp
  tt_metal/impl/dispatch/kernel_config/fd_kernel.cpp
  tt_metal/impl/dispatch/kernel_config/fd_kernel.hpp
  tt_metal/impl/dispatch/kernel_config/mux.cpp
  tt_metal/impl/dispatch/kernel_config/mux.hpp
  tt_metal/impl/dispatch/kernel_config/prefetch.cpp
  tt_metal/impl/dispatch/kernel_config/prefetch.hpp
  tt_metal/impl/dispatch/kernels/cq_dispatch.cpp
  tt_metal/impl/dispatch/kernels/cq_prefetch.cpp
  tt_metal/impl/dispatch/kernels/packet_demux.cpp
  tt_metal/impl/dispatch/kernels/packet_mux.cpp
  tt_metal/impl/dispatch/kernels/packet_queue.hpp
  tt_metal/impl/dispatch/kernels/packet_queue_ctrl.hpp
  tt_metal/impl/dispatch/kernels/vc_eth_tunneler.cpp
  tt_metal/impl/dispatch/kernels/vc_packet_router.cpp
  tt_metal/impl/dispatch/topology.cpp
  tt_metal/impl/dispatch/topology.hpp
  tt_metal/jit_build/build.cpp
  tt_metal/llrt/rtoptions.cpp
Labels: fast-dispatch

#18499 Add tests that exploit multiple queues for multiple devices
  tests/ttnn/unit_tests/gtests/CMakeLists.txt
  tests/ttnn/unit_tests/gtests/multi_thread/test_ccl_multi_cq_multi_device.cpp
  tests/ttnn/unit_tests/gtests/multi_thread/test_utils.cpp
  tests/ttnn/unit_tests/gtests/multi_thread/test_utils.hpp
  tests/ttnn/unit_tests/gtests/ttnn_test_fixtures.hpp
Labels: moreh, training

#18697 Add initial support for Llama3-8B & 70B on BH
  conftest.py
  models/tt_transformers/lt
  models/tt_transformers/tt/mlp.py
  models/tt_transformers/tt/model.py
  models/tt_transformers/tt/model_config.py
  tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py
Labels: P0, blackhole, llama3

#18219 mem benchmark tool
  tt_metal/api/tt-metalium/command_queue_interface.hpp
  tt_metal/impl/dispatch/dispatch_mem_map.cpp
  tt_metal/impl/dispatch/util/dispatch_settings.cpp
  tt_metal/impl/dispatch/util/size_literals.hpp
  tt_metal/tools/CMakeLists.txt
  tt_metal/tools/mem_bench/CMakeLists.txt
  tt_metal/tools/mem_bench/README.md
  tt_metal/tools/mem_bench/context.hpp
  tt_metal/tools/mem_bench/device_utils.cpp
  tt_metal/tools/mem_bench/device_utils.hpp
  tt_metal/tools/mem_bench/host_utils.cpp
  tt_metal/tools/mem_bench/host_utils.hpp
  tt_metal/tools/mem_bench/kernels/mem_bench_kernel.cpp
  tt_metal/tools/mem_bench/mem_bench.cpp
  tt_metal/tools/mem_bench/work_thread.hpp
Labels: fast-dispatch

#18956 Make Logical and SubDevice Logical XY available in kernel
  tests/tt_metal/tt_metal/CMakeLists.txt
  tests/tt_metal/tt_metal/dispatch/dispatch_buffer/test_sub_device.cpp
  tests/tt_metal/tt_metal/dispatch/dispatch_program/test_EnqueueProgram.cpp
  tests/tt_metal/tt_metal/dispatch/dispatch_program/test_program_reuse.cpp
  tests/tt_metal/tt_metal/dispatch/dispatch_program/test_sub_device.cpp
  tests/tt_metal/tt_metal/dispatch/dispatch_test_utils.hpp
  tests/tt_metal/tt_metal/test_kernels/misc/read_my_coordinates.cpp
  tests/tt_metal/tt_metal/test_kernels/misc/runtime_args_kernel.cpp
  tt_metal/api/tt-metalium/dev_msgs.h
  tt_metal/api/tt-metalium/device.hpp
  tt_metal/hw/firmware/src/active_erisc.cc
  tt_metal/hw/firmware/src/brisc.cc
  tt_metal/hw/firmware/src/erisc.cc
  tt_metal/hw/firmware/src/idle_erisc.cc
  tt_metal/hw/firmware/src/ncrisc.cc
  tt_metal/hw/firmware/src/slave_idle_erisc.cc
  tt_metal/hw/firmware/src/trisc.cc
  tt_metal/hw/inc/dataflow_api.h
  tt_metal/hw/inc/risc_common.h
  tt_metal/impl/device/device.cpp
  tt_metal/impl/program/dispatch.cpp
  tt_metal/programming_examples/hello_world_datamovement_kernel/kernels/dataflow/void_dataflow_kernel.cpp
Labels: fast-dispatch

#19154 Delete TSQueue
  tt_metal/impl/dispatch/thread_safe_queue.hpp
Labels: cleanup

#18639 Remove old yolov4 perf test file
  models/demos/wormhole/yolov4/test_yolov4_performant.py
  models/demos/yolov4/tests/yolov4_perfomant.py
  tests/nightly/single_card/yolov4/test_yolov4_performant.py
  tests/nightly/single_card/yolov4/test_yolov4_performant_webdemo.py
Labels: Red_Team_Model

#18777 Llama3 hybrid implementation using submeshes
  models/tt_transformers/PERF.md
  models/tt_transformers/demo/multimodal_demo_chat.py
  models/tt_transformers/demo/multimodal_demo_text.py
  models/tt_transformers/demo/simple_text_demo.py
  models/tt_transformers/demo/simple_vision_demo.py
  models/tt_transformers/lt
  models/tt_transformers/tests/test_accuracy.py
  models/tt_transformers/tests/test_chunked_generation.py
  models/tt_transformers/tests/test_model.py
  models/tt_transformers/tt/common.py
  models/tt_transformers/tt/generator.py
  models/tt_transformers/tt/generator_vllm.py
  models/tt_transformers/tt/model.py
  models/tt_transformers/tt/model_config.py
  models/tt_transformers/tt/multimodal/llama_vision_model.py
Labels: llama3

#19205 Move get_core_type_name into impl
  tt_metal/api/tt-metalium/rtoptions.hpp
  tt_metal/impl/debug/debug_helpers.hpp
  tt_metal/impl/debug/dprint_server.cpp
  tt_metal/impl/debug/watcher_server.cpp
  tt_metal/jit_build/build_env_manager.hpp
Labels: cleanup

#19352 #19198: Return the TensorSpec for the output tensor from query_op_constraints to enable the compiler optimizer
  tests/ttnn/unit_tests/gtests/test_graph_query_op_constraints.cpp
  ttnn/cpp/ttnn/graph/graph_query_op_constraints.hpp
Labels: forge

#19452 Properly setup NOC registers
  tt_metal/hw/firmware/src/active_erisc.cc
Labels: fast-dispatch, blackhole
